Repository Wagu-Wagu/Waffle-party-BE, pull requests merged in 2024-06, with the labels that each got.

#54 [Feat] 게시글 ,댓글 ,답댓글달기 api개발
  src/main/java/com/wagu/wafl/api/common/message/ExceptionMessage.java
  src/main/java/com/wagu/wafl/api/common/message/ResponseMessage.java
  src/main/java/com/wagu/wafl/api/domain/comment/controller/CommentController.java
  src/main/java/com/wagu/wafl/api/domain/comment/dto/request/CreateCommentReplyDTO.java
  src/main/java/com/wagu/wafl/api/domain/comment/dto/request/EditCommentRequestDTO.java
  src/main/java/com/wagu/wafl/api/domain/comment/entity/Comment.java
  src/main/java/com/wagu/wafl/api/domain/comment/service/CommentService.java
  src/main/java/com/wagu/wafl/api/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/wagu/wafl/api/domain/post/controller/PostController.java
  src/main/java/com/wagu/wafl/api/domain/post/dto/request/EditPostRequestDTO.java
  src/main/java/com/wagu/wafl/api/domain/post/entity/Post.java
  src/main/java/com/wagu/wafl/api/domain/post/service/PostService.java
  src/main/java/com/wagu/wafl/api/domain/post/service/PostServiceImpl.java
Labels: gahee, size/M

#56 [Fix] post detail 이미지 리스트 return 추가
  src/main/java/com/wagu/wafl/api/domain/post/dto/response/PostDetailResponseDTO.java
  src/main/java/com/wagu/wafl/api/domain/post/service/PostServiceImpl.java
Labels: suze/S

#58 [FIX] 게시글 수정 api개발 및 s3 Upload api개발
  src/main/java/com/wagu/wafl/api/common/ErrorHandler.java
  src/main/java/com/wagu/wafl/api/common/message/ExceptionMessage.java
  src/main/java/com/wagu/wafl/api/common/message/ResponseMessage.java
  src/main/java/com/wagu/wafl/api/domain/post/controller/PostController.java
  src/main/java/com/wagu/wafl/api/domain/post/dto/request/EditPostRequestDTO.java
  src/main/java/com/wagu/wafl/api/domain/post/dto/request/UploadPostImageRequestDTO.java
  src/main/java/com/wagu/wafl/api/domain/post/dto/response/UploadPostImageResponseDTO.java
  src/main/java/com/wagu/wafl/api/domain/post/service/PostService.java
  src/main/java/com/wagu/wafl/api/domain/post/service/PostServiceImpl.java
Labels: feat, gahee, size/M

#59 [FEAT] 내 소식 생성, 조회, 확인 개발
  src/main/java/com/wagu/wafl/api/common/ErrorHandler.java
  src/main/java/com/wagu/wafl/api/common/exception/AlertException.java
  src/main/java/com/wagu/wafl/api/common/message/ExceptionMessage.java
  src/main/java/com/wagu/wafl/api/common/message/ResponseMessage.java
  src/main/java/com/wagu/wafl/api/domain/alert/entity/Alert.java
  src/main/java/com/wagu/wafl/api/domain/alert/entity/AlertType.java
  src/main/java/com/wagu/wafl/api/domain/alert/repository/AlertRepository.java
  src/main/java/com/wagu/wafl/api/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/wagu/wafl/api/domain/user/controller/UserController.java
  src/main/java/com/wagu/wafl/api/domain/user/dto/response/GetMyNewsResponseDTO.java
  src/main/java/com/wagu/wafl/api/domain/user/entity/User.java
  src/main/java/com/wagu/wafl/api/domain/user/service/UserService.java
  src/main/java/com/wagu/wafl/api/domain/user/service/UserServiceImpl.java
Labels: jjujju, size/M

#64 [FEAT] 글 삭제 개발
  src/main/java/com/wagu/wafl/api/common/message/ResponseMessage.java
  src/main/java/com/wagu/wafl/api/domain/post/controller/PostController.java
  src/main/java/com/wagu/wafl/api/domain/post/entity/Post.java
  src/main/java/com/wagu/wafl/api/domain/post/service/PostService.java
  src/main/java/com/wagu/wafl/api/domain/post/service/PostServiceImpl.java
Labels: feat, jjujju, suze/S

#66 [FIX] 내 소식 리턴값 수정
  src/main/java/com/wagu/wafl/api/domain/user/dto/response/GetMyNewsResponseDTO.java
Labels: fix, jjujju, size/XS
